## Wrapping up

At the end of a session, you would usually want to save your work, which is the code you've been writing. If you haven't yet done so, see the previous section for information about scripts and make sure you have your code saved somewhere as a script you can return to it. The figures can be saved as well, but as long as you have the code and data stored in one place it's always possible to quickly recreate them.

**Keep in mind that Tufts machines are reset every night!** Anything saved directly to a Tufts machine's hard drive will be lost the next day. If there's anything you want to have access to after any lab session, make sure it's saved somewhere else: a network drive, a cloud storage option (like Box or Dropbox), or an external storage (like a USB drive). Since the locations of scripts, data, and other files is really important to doing this kind of work, we will cover more on file systems in the next section.

Congratulations, you've taken a few first steps on your data analysis and visualization odyssey! We've just scratched the surface here, but depending on your familiarity with coding, this may have seemed like a lot of information with very little context. There are some very important things to keep in mind at this point:

First, [no one]{.underline} has every package, function, and argument memorized. In fact, many folks who code spend a lot of their time looking at help documentation and other instances of code for inspiration on how to solve a problem. Like learning a new language, when it comes to learning R it's a good idea to get comfortable with being uncertain.

Second, it's OK if you feel a little lost. There's a lot of hidden knowledge here because coding comes with its own terminology and concepts to describe some pretty abstract things. For example, before this lecture, you may not have understood the word 'argument' to mean a piece of information we give to a function, and it may take awhile longer before it makes its way into your vocabulary in that sense. I will do my best to try and identify instances of this hidden knowledge and point them out. But like anyone who has been doing this a long time, it can be difficult to remember how it feels to be a beginner. So if there is ever a time you feel like we're using a term or concept that isn't familiar, shout it out!

For now take a beat, look at the code you've helped create, and think about the possibilities of what you might do with 5 more weeks of learning. When you're ready, you can move on to complete the In-Class Exercise in the Week 1 Module on Canvas.
