project:
  type: book

book:
  title: "Getting to know R and RStudio"
  author: "Ben Davies"
  date: "5/19/2026"
  chapters:
    - index.qmd
    - 01_Navigating.qmd
    - 02_CommandLine.qmd
    - 03_DataObjects.qmd
    - 04_MyFirstPlot.qmd
    - 05_WrappingUp.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

number-depth: 1

editor: visual


